version: '3.8'

services:
  chat-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ./ChatServer/SignalRChatServer:/app
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
