name: chatclient
description: Chat client example using SignalR Ultra

version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  signalr_ultra:
    path: ../

  # UI e Animações
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Estado e Gerenciamento
  provider: ^6.1.2
  rxdart: ^0.28.0
  
  # Utilitários
  logging: ^1.2.0
  quiver: ^3.2.1
  intl: ^0.19.0
  uuid: ^4.3.3
  
  # UI Components
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^3.1.0
  emoji_picker_flutter: ^1.6.4
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  
  # Notificações
  flutter_local_notifications: ^16.3.2
  
  # Armazenamento
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
